In [1]:
import numpy as np

In [2]:
!pip install numpy

In [5]:
arr = np.array([1,2,3,4,5,6])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [1]:
print(5)

5


In [6]:
print(8)
print(13, end=" ")
print(21)

8
13 21


In [5]:
print(5," ",5)

5 5


In [7]:
print("Hello")
print(" World!")

Hello
 World!


In [16]:
print(f"1 - {1*1}\n2 - {2*2}\n3 - {3*3}\n4 - {4*4}\n5 - {5*5}")

1 - 1
2 - 4
3 - 9
4 - 16
5 - 25


In [21]:
import numpy as np
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [2]:
import numpy as np
np.arange(1,100,6)

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("DataType: ",arr.dtype)

DataType:  int64
