In [2]:
import numpy as np 

In [9]:
arr = np.random.rand(4, 6)
arr

In [11]:
arr = np.arange(1,25).reshape(4,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

<h1>Exercises for Practice</h1>

<h2>01-Create a 3×3 array filled with random numbers and print its shape</h2>

In [17]:
#Code 
import numpy as np
arr = np.random.rand(3, 3)
arr

array([[0.54671028, 0.18485446, 0.96958463],
       [0.77513282, 0.93949894, 0.89482735],
       [0.59789998, 0.92187424, 0.0884925 ]])

In [18]:
print(arr.shape)

(3, 3)


<h2>2.Convert an array of floats [1.1, 2.2, 3.3] into integers
</h2>

In [23]:
#code - 
import numpy as np
arr = np.array([1.1, 2.2, 3.3], dtype=np.int64)
print(arr)

[1 2 3]


<h2>3.Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6] .</h2>

In [29]:
#code - 
arr = np.array([1,2,3,4,5,6])
arr_even=arr%2==0
print(arr_even)
print(arr[arr_even])

[False  True False  True False  True]
[2 4 6]


<h2>04.Reshape a 1D array of size 9 into a 3×3 matrix
</h2>

In [33]:
#code - 
arr = np.array([1,2,3,4,5,6,7,8,9])
arr_reshape = arr.reshape(3,3)
print(arr_reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<h2>05.Use boolean masking to filter numbers greater than 50 in an array</h2>

In [38]:
#code -
arr = np.array([10,20,30,40,50,60,70,80])
arr_mask = arr > 50
print(arr[arr_mask])

[60 70 80]
