<h2>1. Understanding Axes in NumPy</h2>
Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:

1D array → 1 axis (axis 0)
2D array → 2 axes (axis 0 = rows, axis 1 = columns)
3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)
Example: Axes in a 2D Array

In [1]:
import numpy as np

In [12]:
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [11]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [13]:
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


<h1>3. Indexing in 3D Arrays</h1>

For 3D arrays, the first index refers to the "depth" (sheets of data).

In [2]:
import numpy as np
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
 
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [3]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6
 
print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


<h1>4. Practical Example: Selecting Data Along Axes/<h1>

In [4]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

NameError: name 'arr' is not defined

In [5]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)



[[1 2 3]
 [7 8 9]]
