<h2>1. Understanding Axes in NumPy</h2>
Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:

1D array → 1 axis (axis 0)
2D array → 2 axes (axis 0 = rows, axis 1 = columns)
3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)
Example: Axes in a 2D Array

In [1]:
import numpy as np

In [12]:
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [11]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [13]:
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]
