<h1>Rough WOrk</h1>

In [1]:
import numpy as np 

In [3]:
arr = np.array([1,2,3,5,6])
result = arr ** 2
print(result)

[ 1  4  9 25 36]


<h1>Broadcasting in NumPy</h1>

Now, we'll explore how to make your code faster with vectorization and broadcasting in NumPy. These techniques are key to boosting performance in numerical operations by avoiding slow loops and memory inefficiency.

1. Why Loops Are Slow
In Python, loops are typically slow because:

Python’s interpreter: Every iteration of the loop requires Python to interpret the loop logic, which is inherently slower than lower-level, compiled code.
High overhead: Each loop iteration in Python involves additional overhead for function calls, memory access, and index management.
While Python loops are convenient, they don’t take advantage of the optimized memory and computation that libraries like NumPy provide.

Example: Looping Over Arrays in Python

In [4]:
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5])
result = []
 
# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)
 
print(result)  # Output: [1, 4, 9, 16, 25]

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


This works, but it's not efficient. Each loop iteration is slow, especially with large datasets.

2. Vectorization: Fixing the Loop Problem

Vectorization allows you to perform operations on entire arrays at once, instead of iterating over elements one by one. This is made possible by NumPy’s optimized C-based backend that executes operations in compiled code, which is much faster than Python loops.

Vectorized operations are also more readable and compact, making your code easier to maintain.

Example: Vectorized Operation

In [5]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result) 

[ 1  4  9 16 25]


Here, the operation is applied to all elements of the array simultaneously, and it's much faster than looping over the array.

Why is it Faster?

Low-level implementation: NumPy’s vectorized operations are implemented in C (compiled language), which is much faster than Python loops.
Batch processing: NumPy processes multiple elements in parallel using SIMD (Single Instruction, Multiple Data), allowing multiple operations to be done simultaneously.

3. Broadcasting: Scaling Arrays Without Extra Memory


Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes without creating copies. It “stretches” smaller arrays across larger arrays in a memory-efficient way, avoiding the overhead of creating multiple copies of data.

Example: Broadcasting with Scalar
Broadcasting is often used when you want to perform an operation on an array and a scalar value (e.g., add a number to all elements of an array).

In [7]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

[11 12 13 14 15]


Here, the scalar 10 is "broadcast" across the entire array, and no extra memory is used.

4. Broadcasting with Arrays of Different Shapes

Broadcasting becomes more powerful when you apply operations on arrays of different shapes. NumPy automatically adjusts the shapes of arrays to make them compatible for element-wise operations, without actually copying the data.

Example: Broadcasting with Two Arrays

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
 
result = arr1 + arr2  # Element-wise addition
print(result)  # Output: [11 22 33]

[11 22 33]


NumPy automatically aligns the two arrays and performs element-wise addition, treating them as if they have the same shape.